# Generated by Django 3.0.7 on 2020-06-09 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedayregistration',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
