# Generated by Django 3.0.7 on 2020-06-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0016_timeregistration_plan_leaving'),
        ('free_days_registration', '0002_freedayregistration_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedayregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='freedayregistration',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='time_registration.Employee'),
            preserve_default=False,
        ),
    ]
