# Generated by Django 3.0.7 on 2020-06-09 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0003_auto_20200609_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedayregistration',
            name='num_of_days',
        ),
        migrations.AddField(
            model_name='freedayregistration',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freedayregistration',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
