# Generated by Django 3.0.7 on 2020-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0004_auto_20200609_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedayregistration',
            name='note',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
