# Generated by Django 3.0.7 on 2020-06-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0005_freedayregistration_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedayregistration',
            name='free_day_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free_days_registration.FreeDayType'),
        ),
    ]
