# Generated by Django 3.0.7 on 2020-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0006_auto_20200609_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedayregistration',
            name='color',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
    ]
