# Generated by Django 3.0.7 on 2020-06-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0007_freedayregistration_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freedayregistration',
            old_name='color',
            new_name='status',
        ),
    ]
