# Generated by Django 3.0.7 on 2020-06-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0008_auto_20200609_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedayregistration',
            name='is_accepted',
        ),
    ]
