# Generated by Django 3.0.7 on 2020-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0009_remove_freedayregistration_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedayregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'W toku'), ('accepted', 'Zaakceptowany'), ('rejected', 'Odrzucony')], default='pending', max_length=10),
        ),
    ]
