# Generated by Django 3.0.7 on 2020-06-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0016_timeregistration_plan_leaving'),
        ('free_days_registration', '0010_auto_20200610_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedayregistration',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_registration.Employee'),
        ),
    ]
