# Generated by Django 3.0.7 on 2020-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0012_auto_20200610_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedayregistration',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'W toku'), (2, 'Zaakceptowany'), (3, 'Odrzucony')], default=1),
        ),
    ]
