# Generated by Django 3.0.7 on 2020-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_days_registration', '0013_auto_20200610_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedayregistration',
            name='note',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
