# Generated by Django 3.0.5 on 2020-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeregistration',
            name='arrival',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='leaving',
            field=models.TimeField(null=True),
        ),
    ]
