# Generated by Django 3.0.5 on 2020-04-27 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0002_auto_20200427_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeregistration',
            name='arrival',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 27)),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='leaving',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
