# Generated by Django 3.0.5 on 2020-05-01 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0003_auto_20200427_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 15, 11, 57, 632422, tzinfo=utc)),
        ),
    ]
