# Generated by Django 3.0.5 on 2020-05-01 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0004_auto_20200501_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 17, 13, 20, 878910)),
        ),
    ]
