# Generated by Django 3.0.5 on 2020-05-01 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0005_auto_20200501_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 15, 16, 5, 962065, tzinfo=utc)),
        ),
    ]
