# Generated by Django 3.0.5 on 2020-05-01 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0006_auto_20200501_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 17, 39, 42, 140772, tzinfo=utc)),
        ),
    ]
