# Generated by Django 3.0.5 on 2020-05-01 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0007_auto_20200501_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 17, 49, 15, 332653, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='timeregistration',
            name='brakes',
            field=models.ManyToManyField(blank=True, null=True, to='time_registration.Brake'),
        ),
    ]
