# Generated by Django 3.0.5 on 2020-05-01 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0008_auto_20200501_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='brake',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 17, 50, 35, 704553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 17, 50, 35, 705965, tzinfo=utc)),
        ),
    ]
