# Generated by Django 3.0.5 on 2020-05-01 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0010_auto_20200501_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brake',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 18, 18, 0, 154679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 18, 18, 0, 156106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_registration.Employee'),
        ),
    ]
