# Generated by Django 3.0.5 on 2020-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0014_auto_20200503_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeregistration',
            name='brakes',
        ),
        migrations.AddField(
            model_name='timeregistration',
            name='brakes',
            field=models.IntegerField(default=0),
        ),
    ]
