# Generated by Django 3.0.5 on 2020-05-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_registration', '0015_auto_20200503_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeregistration',
            name='plan_leaving',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
